### ISSUE TITLE
Is this still under development?

### ISSUE THREAD

**Issue by bloeys** [emc-advanced-dev/cf-unik-buildpack#1]
Hey,

Just wanted to know if this is still actively being developed alongside the main unik repo. Also, is the source code for the `cf-unik-controller` available? I can't seem to find it anywhere.

Thanks :)

**Comment by ilackarms** [comment]
the cf-unik-buildpack has not been under developed in some time. 

the source is in the `main.go` file itself: https://github.com/solo-io/cf-unik-buildpack/blob/master/main.go

**Comment by bloeys** [comment]
I see, thanks.
Do you know if it is still usable with latest unik releases? or are there potential compatibility problems as unik is developed further?

**Comment by ilackarms** [comment]
@bloeys my guess is that it is still stable with latest unik as our apis have not changed
however i would provide no guarantees here. if you're willing to test it yourself, we'd definitely appreciate hearing your results!

**Comment by bloeys** [comment]
Great then!
I will close this for now, but in case we test this I will make sure to come back and provide feedback ;)
